export const DATA_FETCHING_STARTED = 'DATA_FETCHING_STARTED';
export const DATA_FETCHING_SUCCESS = 'DATA_FETCHING_SUCCESS';
export const DATA_FETCHING_ERROR = 'DATA_FETCHING_ERROR';
export const DELETE_ITEM = 'DELETE_ITEM';
export const SVUOTA_CARRELLO = 'SVUOTA_CARRELLO';